
#Docker_Practical-Partial_examination_2

#Docker compose



version: '3'


services:


  db:

    image: postgres:14

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - db_data:/var/lib/postgresql/data

    networks:
      - tasknet



  backend:

    build: ./backend

    ports:
      - "3000:3000"

    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

    depends_on:
      - db

    networks:
      - tasknet



  web-server:

    image: nginx:alpine

    ports:
      - "80:80"

    volumes:
      - ./web-server:/usr/share/nginx/html
      - ./web-server/nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - backend

    develop:
      watch:	#preview automatically updates as app is edited and save without a need to restart
        - action: sync
          path: .
          target: /app

    networks:
      - tasknet



  volumes:
    db_data:



  networks:
    tasknet:


